<a href="https://colab.research.google.com/github/zetalopez/TRABAJO-ENCARGADO-TP2/blob/master/avance_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# IMPORTANDO DATA DESDE UN URL

import pandas as pd
import numpy as np
data2 = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',sep = ",", header = None,
                  names=['edad','tipo_de_empleo','peso_final','educacion', 
                     'a√±os_educacion','estado _civil','ocupacion','parentesco','raza','sexo','ganancia_capital','perdida_capital','horas_semana','pais','ingresos'])
data2
##Mensaje de prueba

,edad,tipo_de_empleo,peso_final,educacion,a√±os_educacion,estado _civil,ocupacion,parentesco,raza,sexo,ganancia_capital,perdida_capital,horas_semana,pais,ingresos
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [5]:
# tabla de contingencia en porcentajes relativos total
dataframe2 = pd.crosstab(index=data2['educacion'], columns=data2['ingresos'],
            margins=True).apply(lambda r: r/len(data2) ,
                                axis=1)
dataframe2

ingresos          <=50K      >50K       All
educacion
 10th          0.026750  0.001904  0.028654
 11th          0.034243  0.001843  0.036086
 12th          0.012285  0.001013  0.013298
 1st-4th       0.004975  0.000184  0.005160
 5th-6th       0.009736  0.000491  0.010227
 7th-8th       0.018611  0.001228  0.019840
 9th           0.014957  0.000829  0.015786
 Assoc-acdm    0.024631  0.008139  0.032769
 Assoc-voc     0.031357  0.011087  0.042443
 Bachelors     0.096250  0.068210  0.164461
 Doctorate     0.003286  0.009398  0.012684
 HS-grad       0.271060  0.051442  0.322502
 Masters       0.023464  0.029452  0.052916
 Preschool     0.001566  0.000000  0.001566
 Prof-school   0.004699  0.012991  0.017690
 Some-college  0.181321  0.042597  0.223918
All            0.759190  0.240810  1.000000

In [7]:
#funciones

def obtenerMatriz(dataframe):
    np.savetxt("matriz.csv",dataframe)

    matrix = np.genfromtxt('matriz.csv')

    return matrix

def RPE(matrix):
    
    i = len(matrix)#numero de columnas del array
    j = len(matrix[0]) #numero de filas del array

    matrix2 = matrix[0:i-1,0:j-1] #se creo un nuevo array sin los ultimos elementos de cada fila , y los ultimos de cada columna, quedandonos con los restantes, siguiendo el orden del array original.
    maxc = matrix2.max(axis=0)  # obtener maximas probabilidades por columnas del array.
    maxf = matrix2.max(axis=1) # obtener maximos probabilidades por filas del array.

    sumax_columnas = maxc.sum()# suma de los elementos de maxc.

    sumax_filas = maxf.sum()# suma de los elementos de maxf.

    matrix3 = matrix[0:i-1,j-1]#obtenemos la ultima columna del array , para obtener las probabilidades marginales.

    maxtf = matrix3.max()#obtenemos el maximo del array matrix3

    matrix4 = matrix[i-1,0:j-1]#obtenemos la ultima fila del array , para obtener las probabilidades marginales.

    maxtc = matrix4.max()#obtenemos el maximo del array matrix4

    lambdas = (sumax_columnas + sumax_filas - maxtc -maxtf)/(2-maxtc-maxtf)#obteniendo el lambda simetrico

    return lambdas

    print("El estad√≠stico requerido lambda es: ", lambdas)

In [8]:
data = obtenerMatriz(dataframe2)
data

array([[2.67497927e-02, 1.90411842e-03, 2.86539111e-02],
       [3.42434200e-02, 1.84269525e-03, 3.60861153e-02],
       [1.22846350e-02, 1.01348239e-03, 1.32981174e-02],
       [4.97527717e-03, 1.84269525e-04, 5.15954670e-03],
       [9.73557323e-03, 4.91385400e-04, 1.02269586e-02],
       [1.86112220e-02, 1.22846350e-03, 1.98396855e-02],
       [1.49565431e-02, 8.29212862e-04, 1.57857560e-02],
       [2.46306932e-02, 8.13857068e-03, 3.27692638e-02],
       [3.13565308e-02, 1.10868831e-02, 4.24434139e-02],
       [9.62501152e-02, 6.82104358e-02, 1.64460551e-01],
       [3.28613986e-03, 9.39774577e-03, 1.26838856e-02],
       [2.71060471e-01, 5.14419090e-02, 3.22502380e-01],
       [2.34636528e-02, 2.94524124e-02, 5.29160652e-02],
       [1.56629096e-03, 0.00000000e+00, 1.56629096e-03],
       [4.69887288e-03, 1.29910015e-02, 1.76898744e-02],
       [1.81321212e-01, 4.25969718e-02, 2.23918184e-01],
       [7.59190443e-01, 2.40809557e-01, 1.00000000e+00]])

In [10]:
import numpy as np
new=np.array(data)
matriz=new.tolist()
matriz

[[0.026749792696784496, 0.0019041184238813304, 0.02865391112066583],
 [0.03424342004238199, 0.0018426952489174165, 0.03608611529129941],
 [0.012284634992782777, 0.0010134823869045791, 0.013298117379687356],
 [0.004975277172077025, 0.00018426952489174165, 0.005159546696968767],
 [0.009735573231780351, 0.000491385399711311, 0.010226958631491662],
 [0.01861122201406591, 0.0012284634992782777, 0.019839685513344186],
 [0.01495654310371303, 0.0008292128620128375, 0.01578575596572587],
 [0.024630693160529467, 0.00813857068271859, 0.032769263843248055],
 [0.031356530819078035, 0.011086883080986456, 0.042443413900064494],
 [0.09625011516845305, 0.06821043579742637, 0.16446055096587942],
 [0.0032861398605693926, 0.009397745769478825, 0.012683885630048217],
 [0.271060471115752, 0.051441909032277876, 0.32250238014802984],
 [0.023463652836215106, 0.02945241239519671, 0.05291606523141181],
 [0.001566290961579804, 0.0, 0.001566290961579804],
 [0.004698872884739413, 0.012991001504867787, 0.0176898743896072],
 [0.1813212124934738, 0.04259697183747428, 0.22391818433094807],
 [0.7591904425539756, 0.2408095574460244, 1.0]]

## LO HAREMOS POR FUNCIONES
Trabajaremos por funciones el cuadro de contingencia

In [13]:
#1> asumimos que una variable es predominante que otra (en este caso las columnas sobre las filas)
#llamaremos a esta funcion "ydex"
#donde a(una matriz en lista) es el prametro de entrada para esta funcion

def ydex(a):
    
    n=len(a)   #Lectura de la cantidad de elementos de la Matriz    m=len(a[0]) #Longitud de cada elemento 

    ja=a[:n-1] #ja toma el valor de la matriz anterior desde el elemento 0 al n-1 
    print(ja)

    n1=len(ja) #Lectura de la cantidad de elemntos de ja
    m1=len(ja[0]) #Longitud de cada elemento

    print(m1)
    print(n1)
    ma1=[] #Creamos una lista
    for i in range(m1):
        ma1.append([0]*(n1)) #Agregamos a la lista vacia elementos [0]
    print(ma1)



    for i in range(m1): 
        for j in range(n1):
            ma1[i][j]=ja[j][i]
    print(ma1)

    s=0
    for i in range(len(ma1)-1): #Para cada elemento de ma1
        a=max(ma1[i]) #le asignamos el valor max de cada elemento para a
        s=s+a #Sumamos los valores maximos
        a=0
    pmar1=max(ma1[-1]) #Hallamos el valor maximo del ultimo elemento
    print(s)
    print(pmar1)
    resul1=(s-pmar1)/(1-pmar1)
    print(resul1)
    return[s,pmar1,resul1] 

prueba=ydex(matriz)
print('la suma de maximas probabilidades por columnas:',prueba[0])
print('la mayor probabilidad marginal:',prueba[1])
print('el estadistico es:',prueba[2])

la suma de maximas probabilidades por columnas: 0.33927090691317835
la mayor probabilidad marginal: 0.32250238014802984
el estadistico es: 0.024750679963735287

In [15]:
#2> asumimos que una variable es predominante que otra (en este caso las filas sobre las columnas)
#llamaremos a esta funcion "xdey"
#donde a(una matriz en lista) es el prametro de entrada para esta funcion
def xdey(a):
    n=len(a)    
    m=len(a[0])

    ma2=[]
    for i in range(n):
        b=a[i]
        c=b[:m-1]
        ma2.append(c)
    print(ma2)
    
    s=0
    for i in range(len(ma2)-1):
        a=max(ma2[i])
        s=s+a
        #print(s)
    print(round(s,3))

    pmar2=max(ma2[-1])

    resul2=(s-pmar2)/(1-pmar2)
    print(resul2)
    return[s,pmar2,resul2]
prueba=xdey(matriz)
print('la suma de maximas probabilidades por filas:',prueba[0])
print('la mayor probabilidad marginal:',prueba[1])
print('el estadistico es:',prueba[2])

la suma de maximas probabilidades por filas: 0.779582936641995
la mayor probabilidad marginal: 0.7591904425539756
el estadistico es: 0.08468307613824744

In [16]:
# las versiones anteriores se dednominan asimetricos porque al intercambiar la variable respuestas con la explicativa, el valor de los estadisticos no siempr es igual
#pero requeriremos de simtrica del coeficinete lambda
#3> para este caso haremos una version simetrica
def asime(a):
    t=  ydex(a)
    t1=t[0]
    t2=t[1]
    p=  xdey(a)
    p1=p[0]
    p2=p[1]

    lam=(t1+p1-t2-p2)/(2-t2-p2)
    return lam
prueba=asime(matriz)
print('el estadistico lambda es:',prueba)

el estadistico lambda es: 0.040466874017591456